server:
  tomcat:
    uri-encoding: UTF-8
  #???
  port: 8080
  servlet:
    # ????
    context-path: /dems
    session:
      cookie:
        http-only: true
spring:
  profiles:
    active: db,knife4j,satoken

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    edu.sugon.demsbackend.dao: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl